services:
  config-service:
    image: melita/config-service
    build: ./config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  order-service:
    image: melita/order-service
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - config-service

  notification-service:
    image: melita/notification-service
    build: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - config-service

  order-processing-service:
    image: melita/order-processing-service
    build: ./order-processing-service
    ports:
      - "8084:8084"
    depends_on:
      - config-service

  auth-service:
    image: melita/auth-service
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - config-service

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=orders'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - '5672'
